[build]
  command = """
    python3.8 -m pip install --upgrade pip &&
    python3.8 -m pip install -r requirements.txt &&
    mkdir -p netlify/functions &&
    cp -r templates static netlify/functions/
  """
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.8.12"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
