services:
  - type: web
    name: meseri-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        value: mysql://hperezc97:geoHCP97@mysql-hperezc97.alwaysdata.net/hperezc97_meseribd
      - key: SECRET_KEY
        value: d978422048d1ad28cf337105b9dc5bad
      - key: FLASK_ENV
        value: production
